package com.google.android.gms.fitness;

/* JADX INFO: compiled from: com.google.android.gms:play-services-fitness@@18.0.0 */
/* JADX INFO: loaded from: classes.dex */
public class FitnessActivities {
    public static final java.lang.String AEROBICS = "aerobics";
    public static final java.lang.String ARCHERY = "archery";
    public static final java.lang.String BADMINTON = "badminton";
    public static final java.lang.String BASEBALL = "baseball";
    public static final java.lang.String BASKETBALL = "basketball";
    public static final java.lang.String BIATHLON = "biathlon";
    public static final java.lang.String BIKING = "biking";
    public static final java.lang.String BIKING_HAND = "biking.hand";
    public static final java.lang.String BIKING_MOUNTAIN = "biking.mountain";
    public static final java.lang.String BIKING_ROAD = "biking.road";
    public static final java.lang.String BIKING_SPINNING = "biking.spinning";
    public static final java.lang.String BIKING_STATIONARY = "biking.stationary";
    public static final java.lang.String BIKING_UTILITY = "biking.utility";
    public static final java.lang.String BOXING = "boxing";
    public static final java.lang.String CALISTHENICS = "calisthenics";
    public static final java.lang.String CIRCUIT_TRAINING = "circuit_training";
    public static final java.lang.String CRICKET = "cricket";
    public static final java.lang.String CROSSFIT = "crossfit";
    public static final java.lang.String CURLING = "curling";
    public static final java.lang.String DANCING = "dancing";
    public static final java.lang.String DIVING = "diving";
    public static final java.lang.String ELEVATOR = "elevator";
    public static final java.lang.String ELLIPTICAL = "elliptical";
    public static final java.lang.String ERGOMETER = "ergometer";
    public static final java.lang.String ESCALATOR = "escalator";
    public static final java.lang.String EXTRA_STATUS = "actionStatus";
    public static final java.lang.String FENCING = "fencing";
    public static final java.lang.String FOOTBALL_AMERICAN = "football.american";
    public static final java.lang.String FOOTBALL_AUSTRALIAN = "football.australian";
    public static final java.lang.String FOOTBALL_SOCCER = "football.soccer";
    public static final java.lang.String FRISBEE_DISC = "frisbee_disc";
    public static final java.lang.String GARDENING = "gardening";
    public static final java.lang.String GOLF = "golf";
    public static final java.lang.String GYMNASTICS = "gymnastics";
    public static final java.lang.String HANDBALL = "handball";
    public static final java.lang.String HIGH_INTENSITY_INTERVAL_TRAINING = "interval_training.high_intensity";
    public static final java.lang.String HIKING = "hiking";
    public static final java.lang.String HOCKEY = "hockey";
    public static final java.lang.String HORSEBACK_RIDING = "horseback_riding";
    public static final java.lang.String HOUSEWORK = "housework";
    public static final java.lang.String ICE_SKATING = "ice_skating";
    public static final java.lang.String INTERVAL_TRAINING = "interval_training";
    public static final java.lang.String IN_VEHICLE = "in_vehicle";
    public static final java.lang.String JUMP_ROPE = "jump_rope";
    public static final java.lang.String KAYAKING = "kayaking";
    public static final java.lang.String KETTLEBELL_TRAINING = "kettlebell_training";
    public static final java.lang.String KICKBOXING = "kickboxing";
    public static final java.lang.String KICK_SCOOTER = "kick_scooter";
    public static final java.lang.String KITESURFING = "kitesurfing";
    public static final java.lang.String MARTIAL_ARTS = "martial_arts";
    public static final java.lang.String MEDITATION = "meditation";
    public static final java.lang.String MIME_TYPE_PREFIX = "vnd.google.fitness.activity/";
    public static final java.lang.String MIXED_MARTIAL_ARTS = "martial_arts.mixed";
    public static final java.lang.String ON_FOOT = "on_foot";
    public static final java.lang.String OTHER = "other";
    public static final java.lang.String P90X = "p90x";
    public static final java.lang.String PARAGLIDING = "paragliding";
    public static final java.lang.String PILATES = "pilates";
    public static final java.lang.String POLO = "polo";
    public static final java.lang.String RACQUETBALL = "racquetball";
    public static final java.lang.String ROCK_CLIMBING = "rock_climbing";
    public static final java.lang.String ROWING = "rowing";
    public static final java.lang.String ROWING_MACHINE = "rowing.machine";
    public static final java.lang.String RUGBY = "rugby";
    public static final java.lang.String RUNNING = "running";
    public static final java.lang.String RUNNING_JOGGING = "running.jogging";
    public static final java.lang.String RUNNING_SAND = "running.sand";
    public static final java.lang.String RUNNING_TREADMILL = "running.treadmill";
    public static final java.lang.String SAILING = "sailing";
    public static final java.lang.String SCUBA_DIVING = "scuba_diving";
    public static final java.lang.String SKATEBOARDING = "skateboarding";
    public static final java.lang.String SKATING = "skating";
    public static final java.lang.String SKATING_CROSS = "skating.cross";
    public static final java.lang.String SKATING_INDOOR = "skating.indoor";
    public static final java.lang.String SKATING_INLINE = "skating.inline";
    public static final java.lang.String SKIING = "skiing";
    public static final java.lang.String SKIING_BACK_COUNTRY = "skiing.back_country";
    public static final java.lang.String SKIING_CROSS_COUNTRY = "skiing.cross_country";
    public static final java.lang.String SKIING_DOWNHILL = "skiing.downhill";
    public static final java.lang.String SKIING_KITE = "skiing.kite";
    public static final java.lang.String SKIING_ROLLER = "skiing.roller";
    public static final java.lang.String SLEDDING = "sledding";
    public static final java.lang.String SLEEP = "sleep";
    public static final java.lang.String SLEEP_AWAKE = "sleep.awake";
    public static final java.lang.String SLEEP_DEEP = "sleep.deep";
    public static final java.lang.String SLEEP_LIGHT = "sleep.light";
    public static final java.lang.String SLEEP_REM = "sleep.rem";
    public static final java.lang.String SNOWBOARDING = "snowboarding";
    public static final java.lang.String SNOWMOBILE = "snowmobile";
    public static final java.lang.String SNOWSHOEING = "snowshoeing";
    public static final java.lang.String SOFTBALL = "softball";
    public static final java.lang.String SQUASH = "squash";
    public static final java.lang.String STAIR_CLIMBING = "stair_climbing";
    public static final java.lang.String STAIR_CLIMBING_MACHINE = "stair_climbing.machine";
    public static final java.lang.String STANDUP_PADDLEBOARDING = "standup_paddleboarding";
    public static final java.lang.String STATUS_ACTIVE = "ActiveActionStatus";
    public static final java.lang.String STATUS_COMPLETED = "CompletedActionStatus";
    public static final java.lang.String STILL = "still";
    public static final java.lang.String STRENGTH_TRAINING = "strength_training";
    public static final java.lang.String SURFING = "surfing";
    public static final java.lang.String SWIMMING = "swimming";
    public static final java.lang.String SWIMMING_OPEN_WATER = "swimming.open_water";
    public static final java.lang.String SWIMMING_POOL = "swimming.pool";
    public static final java.lang.String TABLE_TENNIS = "table_tennis";
    public static final java.lang.String TEAM_SPORTS = "team_sports";
    public static final java.lang.String TENNIS = "tennis";
    public static final java.lang.String TILTING = "tilting";

    @java.lang.Deprecated
    public static final java.lang.String TREADMILL = "treadmill";
    public static final java.lang.String UNKNOWN = "unknown";
    public static final java.lang.String VOLLEYBALL = "volleyball";
    public static final java.lang.String VOLLEYBALL_BEACH = "volleyball.beach";
    public static final java.lang.String VOLLEYBALL_INDOOR = "volleyball.indoor";
    public static final java.lang.String WAKEBOARDING = "wakeboarding";
    public static final java.lang.String WALKING = "walking";
    public static final java.lang.String WALKING_FITNESS = "walking.fitness";
    public static final java.lang.String WALKING_NORDIC = "walking.nordic";
    public static final java.lang.String WALKING_STROLLER = "walking.stroller";
    public static final java.lang.String WALKING_TREADMILL = "walking.treadmill";
    public static final java.lang.String WATER_POLO = "water_polo";
    public static final java.lang.String WEIGHTLIFTING = "weightlifting";
    public static final java.lang.String WHEELCHAIR = "wheelchair";
    public static final java.lang.String WINDSURFING = "windsurfing";
    public static final java.lang.String YOGA = "yoga";
    public static final java.lang.String ZUMBA = "zumba";

    FitnessActivities() {
    }

    public static java.lang.String getMimeType(java.lang.String str) {
        return com.google.android.gms.internal.fitness.zzjn.getMimeType(str);
    }
}
