package kotlin.reflect.jvm.internal.impl.metadata.builtins;

/* JADX INFO: loaded from: classes2.dex */
public final class BuiltInsProtoBuf {
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Package, java.lang.Integer> packageFqName = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newSingularGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Package.getDefaultInstance(), 0, null, null, 151, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.INT32, java.lang.Integer.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Class, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> classAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Class.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, powerwatch.matrix.com.pwgen2android.utils.UserPrefsUtilsKt.metricWeightMax, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Constructor, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> constructorAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Constructor.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, powerwatch.matrix.com.pwgen2android.utils.UserPrefsUtilsKt.metricWeightMax, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Function, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> functionAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Function.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, powerwatch.matrix.com.pwgen2android.utils.UserPrefsUtilsKt.metricWeightMax, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Property, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> propertyAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Property.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, powerwatch.matrix.com.pwgen2android.utils.UserPrefsUtilsKt.metricWeightMax, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Property, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> propertyGetterAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Property.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, 152, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Property, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> propertySetterAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Property.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, 153, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Property, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.Argument.Value> compileTimeValue = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newSingularGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Property.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.Argument.Value.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.Argument.Value.getDefaultInstance(), null, 151, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.Argument.Value.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.EnumEntry, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> enumEntryAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.EnumEntry.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, powerwatch.matrix.com.pwgen2android.utils.UserPrefsUtilsKt.metricWeightMax, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.ValueParameter, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> parameterAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.ValueParameter.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, powerwatch.matrix.com.pwgen2android.utils.UserPrefsUtilsKt.metricWeightMax, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Type, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> typeAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Type.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, powerwatch.matrix.com.pwgen2android.utils.UserPrefsUtilsKt.metricWeightMax, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);
    public static final kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.GeneratedExtension<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.TypeParameter, java.util.List<kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation>> typeParameterAnnotation = kotlin.reflect.jvm.internal.impl.protobuf.GeneratedMessageLite.newRepeatedGeneratedExtension(kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.TypeParameter.getDefaultInstance(), kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.getDefaultInstance(), null, powerwatch.matrix.com.pwgen2android.utils.UserPrefsUtilsKt.metricWeightMax, kotlin.reflect.jvm.internal.impl.protobuf.WireFormat.FieldType.MESSAGE, false, kotlin.reflect.jvm.internal.impl.metadata.ProtoBuf.Annotation.class);

    public static void registerAllExtensions(kotlin.reflect.jvm.internal.impl.protobuf.ExtensionRegistryLite extensionRegistryLite) {
        extensionRegistryLite.add(packageFqName);
        extensionRegistryLite.add(classAnnotation);
        extensionRegistryLite.add(constructorAnnotation);
        extensionRegistryLite.add(functionAnnotation);
        extensionRegistryLite.add(propertyAnnotation);
        extensionRegistryLite.add(propertyGetterAnnotation);
        extensionRegistryLite.add(propertySetterAnnotation);
        extensionRegistryLite.add(compileTimeValue);
        extensionRegistryLite.add(enumEntryAnnotation);
        extensionRegistryLite.add(parameterAnnotation);
        extensionRegistryLite.add(typeAnnotation);
        extensionRegistryLite.add(typeParameterAnnotation);
    }
}
