package kotlin.reflect.jvm.internal.impl.util;

/* JADX INFO: compiled from: OperatorNameConventions.kt */
/* JADX INFO: loaded from: classes2.dex */
public final class OperatorNameConventions {
    public static final kotlin.reflect.jvm.internal.impl.name.Name AND;
    public static final java.util.Set<kotlin.reflect.jvm.internal.impl.name.Name> ASSIGNMENT_OPERATIONS;
    public static final java.util.Set<kotlin.reflect.jvm.internal.impl.name.Name> BINARY_OPERATION_NAMES;
    public static final kotlin.reflect.jvm.internal.impl.name.Name COMPARE_TO;
    public static final kotlin.text.Regex COMPONENT_REGEX;
    public static final kotlin.reflect.jvm.internal.impl.name.Name CONTAINS;
    public static final kotlin.reflect.jvm.internal.impl.name.Name DEC;
    public static final kotlin.reflect.jvm.internal.impl.name.Name DIV;
    public static final kotlin.reflect.jvm.internal.impl.name.Name DIV_ASSIGN;
    public static final kotlin.reflect.jvm.internal.impl.name.Name EQUALS;
    public static final kotlin.reflect.jvm.internal.impl.name.Name GET;
    public static final kotlin.reflect.jvm.internal.impl.name.Name GET_VALUE;
    public static final kotlin.reflect.jvm.internal.impl.name.Name HAS_NEXT;
    public static final kotlin.reflect.jvm.internal.impl.name.Name INC;
    public static final kotlin.reflect.jvm.internal.impl.util.OperatorNameConventions INSTANCE = new kotlin.reflect.jvm.internal.impl.util.OperatorNameConventions();
    public static final kotlin.reflect.jvm.internal.impl.name.Name INVOKE;
    public static final kotlin.reflect.jvm.internal.impl.name.Name ITERATOR;
    public static final kotlin.reflect.jvm.internal.impl.name.Name MINUS;
    public static final kotlin.reflect.jvm.internal.impl.name.Name MINUS_ASSIGN;
    public static final kotlin.reflect.jvm.internal.impl.name.Name MOD;
    public static final kotlin.reflect.jvm.internal.impl.name.Name MOD_ASSIGN;
    public static final kotlin.reflect.jvm.internal.impl.name.Name NEXT;
    public static final kotlin.reflect.jvm.internal.impl.name.Name NOT;
    public static final kotlin.reflect.jvm.internal.impl.name.Name OR;
    public static final kotlin.reflect.jvm.internal.impl.name.Name PLUS;
    public static final kotlin.reflect.jvm.internal.impl.name.Name PLUS_ASSIGN;
    public static final kotlin.reflect.jvm.internal.impl.name.Name PROVIDE_DELEGATE;
    public static final kotlin.reflect.jvm.internal.impl.name.Name RANGE_TO;
    public static final kotlin.reflect.jvm.internal.impl.name.Name REM;
    public static final kotlin.reflect.jvm.internal.impl.name.Name REM_ASSIGN;
    public static final kotlin.reflect.jvm.internal.impl.name.Name SET;
    public static final kotlin.reflect.jvm.internal.impl.name.Name SET_VALUE;
    public static final java.util.Set<kotlin.reflect.jvm.internal.impl.name.Name> SIMPLE_UNARY_OPERATION_NAMES;
    public static final kotlin.reflect.jvm.internal.impl.name.Name TIMES;
    public static final kotlin.reflect.jvm.internal.impl.name.Name TIMES_ASSIGN;
    public static final kotlin.reflect.jvm.internal.impl.name.Name UNARY_MINUS;
    public static final java.util.Set<kotlin.reflect.jvm.internal.impl.name.Name> UNARY_OPERATION_NAMES;
    public static final kotlin.reflect.jvm.internal.impl.name.Name UNARY_PLUS;

    static {
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier = kotlin.reflect.jvm.internal.impl.name.Name.identifier("getValue");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier, "Name.identifier(\"getValue\")");
        GET_VALUE = nameIdentifier;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier2 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("setValue");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier2, "Name.identifier(\"setValue\")");
        SET_VALUE = nameIdentifier2;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier3 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("provideDelegate");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier3, "Name.identifier(\"provideDelegate\")");
        PROVIDE_DELEGATE = nameIdentifier3;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier4 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("equals");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier4, "Name.identifier(\"equals\")");
        EQUALS = nameIdentifier4;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier5 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("compareTo");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier5, "Name.identifier(\"compareTo\")");
        COMPARE_TO = nameIdentifier5;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier6 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("contains");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier6, "Name.identifier(\"contains\")");
        CONTAINS = nameIdentifier6;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier7 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("invoke");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier7, "Name.identifier(\"invoke\")");
        INVOKE = nameIdentifier7;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier8 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("iterator");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier8, "Name.identifier(\"iterator\")");
        ITERATOR = nameIdentifier8;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier9 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("get");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier9, "Name.identifier(\"get\")");
        GET = nameIdentifier9;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier10 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("set");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier10, "Name.identifier(\"set\")");
        SET = nameIdentifier10;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier11 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("next");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier11, "Name.identifier(\"next\")");
        NEXT = nameIdentifier11;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier12 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("hasNext");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier12, "Name.identifier(\"hasNext\")");
        HAS_NEXT = nameIdentifier12;
        COMPONENT_REGEX = new kotlin.text.Regex("component\\d+");
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier13 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("and");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier13, "Name.identifier(\"and\")");
        AND = nameIdentifier13;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier14 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("or");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier14, "Name.identifier(\"or\")");
        OR = nameIdentifier14;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier15 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("inc");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier15, "Name.identifier(\"inc\")");
        INC = nameIdentifier15;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier16 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("dec");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier16, "Name.identifier(\"dec\")");
        DEC = nameIdentifier16;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier17 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("plus");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier17, "Name.identifier(\"plus\")");
        PLUS = nameIdentifier17;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier18 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("minus");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier18, "Name.identifier(\"minus\")");
        MINUS = nameIdentifier18;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier19 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("not");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier19, "Name.identifier(\"not\")");
        NOT = nameIdentifier19;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier20 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("unaryMinus");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier20, "Name.identifier(\"unaryMinus\")");
        UNARY_MINUS = nameIdentifier20;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier21 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("unaryPlus");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier21, "Name.identifier(\"unaryPlus\")");
        UNARY_PLUS = nameIdentifier21;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier22 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("times");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier22, "Name.identifier(\"times\")");
        TIMES = nameIdentifier22;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier23 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("div");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier23, "Name.identifier(\"div\")");
        DIV = nameIdentifier23;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier24 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("mod");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier24, "Name.identifier(\"mod\")");
        MOD = nameIdentifier24;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier25 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("rem");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier25, "Name.identifier(\"rem\")");
        REM = nameIdentifier25;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier26 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("rangeTo");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier26, "Name.identifier(\"rangeTo\")");
        RANGE_TO = nameIdentifier26;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier27 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("timesAssign");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier27, "Name.identifier(\"timesAssign\")");
        TIMES_ASSIGN = nameIdentifier27;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier28 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("divAssign");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier28, "Name.identifier(\"divAssign\")");
        DIV_ASSIGN = nameIdentifier28;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier29 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("modAssign");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier29, "Name.identifier(\"modAssign\")");
        MOD_ASSIGN = nameIdentifier29;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier30 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("remAssign");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier30, "Name.identifier(\"remAssign\")");
        REM_ASSIGN = nameIdentifier30;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier31 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("plusAssign");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier31, "Name.identifier(\"plusAssign\")");
        PLUS_ASSIGN = nameIdentifier31;
        kotlin.reflect.jvm.internal.impl.name.Name nameIdentifier32 = kotlin.reflect.jvm.internal.impl.name.Name.identifier("minusAssign");
        kotlin.jvm.internal.Intrinsics.checkExpressionValueIsNotNull(nameIdentifier32, "Name.identifier(\"minusAssign\")");
        MINUS_ASSIGN = nameIdentifier32;
        UNARY_OPERATION_NAMES = kotlin.collections.SetsKt.setOf((java.lang.Object[]) new kotlin.reflect.jvm.internal.impl.name.Name[]{nameIdentifier15, nameIdentifier16, nameIdentifier21, nameIdentifier20, nameIdentifier19});
        SIMPLE_UNARY_OPERATION_NAMES = kotlin.collections.SetsKt.setOf((java.lang.Object[]) new kotlin.reflect.jvm.internal.impl.name.Name[]{nameIdentifier21, nameIdentifier20, nameIdentifier19});
        BINARY_OPERATION_NAMES = kotlin.collections.SetsKt.setOf((java.lang.Object[]) new kotlin.reflect.jvm.internal.impl.name.Name[]{nameIdentifier22, nameIdentifier17, nameIdentifier18, nameIdentifier23, nameIdentifier24, nameIdentifier25, nameIdentifier26});
        ASSIGNMENT_OPERATIONS = kotlin.collections.SetsKt.setOf((java.lang.Object[]) new kotlin.reflect.jvm.internal.impl.name.Name[]{nameIdentifier27, nameIdentifier28, nameIdentifier29, nameIdentifier30, nameIdentifier31, nameIdentifier32});
    }

    private OperatorNameConventions() {
    }
}
