package com.google.android.gms.measurement.internal;

/* JADX INFO: compiled from: com.google.android.gms:play-services-measurement-impl@@17.2.3 */
/* JADX INFO: loaded from: classes.dex */
public final class zzap {
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzaa;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzab;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzac;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzad;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzae;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzaf;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzag;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzah;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzai;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.String> zzaj;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzak;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzal;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Double> zzam;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzan;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzao;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzap;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzaq;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzar;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzas;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzat;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzau;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzav;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzaw;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzax;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzay;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzaz;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzba;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbb;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbc;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbd;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbe;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbf;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbg;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbh;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbi;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbj;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbk;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbl;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbm;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbn;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbo;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbp;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbq;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbr;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbs;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbt;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbu;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbv;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbw;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbx;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzby;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzbz;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzca;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcb;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcc;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcd;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzce;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcf;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcg;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzch;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzci;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcj;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzck;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcl;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcm;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcn;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzco;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcp;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcq;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcr;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcs;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzct;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcu;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcv;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcw;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcx;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcy;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzcz;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzda;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzdb;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzdc;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzdd;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzde;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzdf;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzdg;
    private static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzdj;
    private static com.google.android.gms.measurement.internal.zzez<java.lang.Boolean> zzdk;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzl;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzm;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzn;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzo;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.String> zzp;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzq;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzr;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzs;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzt;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzu;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzv;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzw;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzx;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzy;
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzz;
    private static java.util.List<com.google.android.gms.measurement.internal.zzez<?>> zzdh = java.util.Collections.synchronizedList(new java.util.ArrayList());
    private static java.util.Set<com.google.android.gms.measurement.internal.zzez<?>> zzdi = java.util.Collections.synchronizedSet(new java.util.HashSet());
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zza = zza("measurement.ad_id_cache_time", 10000L, 10000L, com.google.android.gms.measurement.internal.zzas.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzb = zza("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, com.google.android.gms.measurement.internal.zzar.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Long> zzc = zza("measurement.config.cache_time", 86400000L, 3600000L, com.google.android.gms.measurement.internal.zzbo.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.String> zzd = zza("measurement.config.url_scheme", "https", "https", com.google.android.gms.measurement.internal.zzbx.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.String> zze = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", com.google.android.gms.measurement.internal.zzck.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzf = zza("measurement.upload.max_bundles", 100, 100, com.google.android.gms.measurement.internal.zzct.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzg = zza("measurement.upload.max_batch_size", 65536, 65536, com.google.android.gms.measurement.internal.zzdg.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzh = zza("measurement.upload.max_bundle_size", 65536, 65536, com.google.android.gms.measurement.internal.zzdp.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzi = zza("measurement.upload.max_events_per_bundle", 1000, 1000, com.google.android.gms.measurement.internal.zzec.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzj = zza("measurement.upload.max_events_per_day", 100000, 100000, com.google.android.gms.measurement.internal.zzel.zza);
    public static com.google.android.gms.measurement.internal.zzez<java.lang.Integer> zzk = zza("measurement.upload.max_error_events_per_day", 1000, 1000, com.google.android.gms.measurement.internal.zzau.zza);

    public static java.util.Map<java.lang.String, java.lang.String> zza(android.content.Context context) {
        com.google.android.gms.internal.measurement.zzbx zzbxVarZza = com.google.android.gms.internal.measurement.zzbx.zza(context.getContentResolver(), com.google.android.gms.internal.measurement.zzcm.zza("com.google.android.gms.measurement"));
        return zzbxVarZza == null ? java.util.Collections.emptyMap() : zzbxVarZza.zza();
    }

    private static <V> com.google.android.gms.measurement.internal.zzez<V> zza(java.lang.String str, V v, V v2, com.google.android.gms.measurement.internal.zzex<V> zzexVar) {
        com.google.android.gms.measurement.internal.zzez<V> zzezVar = new com.google.android.gms.measurement.internal.zzez<>(str, v, v2, zzexVar);
        zzdh.add(zzezVar);
        return zzezVar;
    }

    static final /* synthetic */ java.lang.Long zzdd() {
        if (com.google.android.gms.measurement.internal.zzfa.zza != null) {
            com.google.android.gms.measurement.internal.zzw zzwVar = com.google.android.gms.measurement.internal.zzfa.zza;
        }
        return java.lang.Long.valueOf(com.google.android.gms.internal.measurement.zzjd.zzc());
    }

    static {
        java.lang.Integer numValueOf = java.lang.Integer.valueOf(net.sqlcipher.database.SQLiteDatabase.SQLITE_MAX_LIKE_PATTERN_LENGTH);
        zzl = zza("measurement.upload.max_public_events_per_day", numValueOf, numValueOf, com.google.android.gms.measurement.internal.zzbd.zza);
        zzm = zza("measurement.upload.max_conversions_per_day", 10000, 10000, com.google.android.gms.measurement.internal.zzbg.zza);
        zzn = zza("measurement.upload.max_realtime_events_per_day", 10, 10, com.google.android.gms.measurement.internal.zzbf.zza);
        zzo = zza("measurement.store.max_stored_events_per_app", 100000, 100000, com.google.android.gms.measurement.internal.zzbi.zza);
        zzp = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", com.google.android.gms.measurement.internal.zzbh.zza);
        zzq = zza("measurement.upload.backoff_period", 43200000L, 43200000L, com.google.android.gms.measurement.internal.zzbk.zza);
        zzr = zza("measurement.upload.window_interval", 3600000L, 3600000L, com.google.android.gms.measurement.internal.zzbj.zza);
        zzs = zza("measurement.upload.interval", 3600000L, 3600000L, com.google.android.gms.measurement.internal.zzbm.zza);
        zzt = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, com.google.android.gms.measurement.internal.zzbl.zza);
        zzu = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, com.google.android.gms.measurement.internal.zzbn.zza);
        zzv = zza("measurement.upload.minimum_delay", 500L, 500L, com.google.android.gms.measurement.internal.zzbq.zza);
        zzw = zza("measurement.alarm_manager.minimum_interval", 60000L, 60000L, com.google.android.gms.measurement.internal.zzbp.zza);
        zzx = zza("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, com.google.android.gms.measurement.internal.zzbs.zza);
        zzy = zza("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, com.google.android.gms.measurement.internal.zzbr.zza);
        zzz = zza("measurement.upload.initial_upload_delay_time", 15000L, 15000L, com.google.android.gms.measurement.internal.zzbu.zza);
        zzaa = zza("measurement.upload.retry_time", 1800000L, 1800000L, com.google.android.gms.measurement.internal.zzbt.zza);
        zzab = zza("measurement.upload.retry_count", 6, 6, com.google.android.gms.measurement.internal.zzbw.zza);
        zzac = zza("measurement.upload.max_queue_time", 2419200000L, 2419200000L, com.google.android.gms.measurement.internal.zzbv.zza);
        zzad = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, com.google.android.gms.measurement.internal.zzby.zza);
        zzae = zza("measurement.audience.filter_result_max_count", 200, 200, com.google.android.gms.measurement.internal.zzca.zza);
        zzaf = zza("measurement.upload.max_public_user_properties", 25, 25, null);
        java.lang.Integer numValueOf2 = java.lang.Integer.valueOf(com.baidu.mapapi.UIMsg.d_ResultType.SHORT_URL);
        zzag = zza("measurement.upload.max_event_name_cardinality", numValueOf2, numValueOf2, null);
        zzah = zza("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, com.google.android.gms.measurement.internal.zzbz.zza);
        zzai = zza("measurement.test.boolean_flag", false, false, com.google.android.gms.measurement.internal.zzcc.zza);
        zzaj = zza("measurement.test.string_flag", "---", "---", com.google.android.gms.measurement.internal.zzcb.zza);
        zzak = zza("measurement.test.long_flag", -1L, -1L, com.google.android.gms.measurement.internal.zzce.zza);
        zzal = zza("measurement.test.int_flag", -2, -2, com.google.android.gms.measurement.internal.zzcd.zza);
        java.lang.Double dValueOf = java.lang.Double.valueOf(-3.0d);
        zzam = zza("measurement.test.double_flag", dValueOf, dValueOf, com.google.android.gms.measurement.internal.zzcg.zza);
        zzan = zza("measurement.experiment.max_ids", 50, 50, com.google.android.gms.measurement.internal.zzcf.zza);
        zzao = zza("measurement.max_bundles_per_iteration", 1, 1, com.google.android.gms.measurement.internal.zzci.zza);
        zzap = zza("measurement.validation.internal_limits_internal_event_params", false, false, com.google.android.gms.measurement.internal.zzch.zza);
        zzaq = zza("measurement.referrer.enable_logging_install_referrer_cmp_from_apk", false, false, com.google.android.gms.measurement.internal.zzcj.zza);
        zzar = zza("measurement.client.sessions.session_id_enabled", true, true, com.google.android.gms.measurement.internal.zzcm.zza);
        zzas = zza("measurement.service.sessions.session_number_enabled", true, true, com.google.android.gms.measurement.internal.zzcl.zza);
        zzat = zza("measurement.client.sessions.background_sessions_enabled", true, true, com.google.android.gms.measurement.internal.zzco.zza);
        zzau = zza("measurement.client.sessions.remove_expired_session_properties_enabled", true, true, com.google.android.gms.measurement.internal.zzcn.zza);
        zzav = zza("measurement.service.sessions.session_number_backfill_enabled", true, true, com.google.android.gms.measurement.internal.zzcq.zza);
        zzaw = zza("measurement.service.sessions.remove_disabled_session_number", true, true, com.google.android.gms.measurement.internal.zzcp.zza);
        zzax = zza("measurement.client.sessions.start_session_before_view_screen", true, true, com.google.android.gms.measurement.internal.zzcs.zza);
        zzay = zza("measurement.client.sessions.check_on_startup", true, true, com.google.android.gms.measurement.internal.zzcr.zza);
        zzaz = zza("measurement.collection.firebase_global_collection_flag_enabled", true, true, com.google.android.gms.measurement.internal.zzcu.zza);
        zzba = zza("measurement.collection.efficient_engagement_reporting_enabled_2", false, false, com.google.android.gms.measurement.internal.zzcw.zza);
        zzbb = zza("measurement.collection.redundant_engagement_removal_enabled", false, false, com.google.android.gms.measurement.internal.zzcv.zza);
        zzbc = zza("measurement.personalized_ads_signals_collection_enabled", true, true, com.google.android.gms.measurement.internal.zzcy.zza);
        zzbd = zza("measurement.personalized_ads_property_translation_enabled", true, true, com.google.android.gms.measurement.internal.zzcx.zza);
        zzbe = zza("measurement.experiment.enable_experiment_reporting", true, true, com.google.android.gms.measurement.internal.zzda.zza);
        zzbf = zza("measurement.collection.log_event_and_bundle_v2", true, true, com.google.android.gms.measurement.internal.zzcz.zza);
        zzbg = zza("measurement.quality.checksum", false, false, null);
        zzbh = zza("measurement.module.collection.conditionally_omit_admob_app_id", true, true, com.google.android.gms.measurement.internal.zzdc.zza);
        zzbi = zza("measurement.sdk.dynamite.use_dynamite2", false, false, com.google.android.gms.measurement.internal.zzdb.zza);
        zzbj = zza("measurement.sdk.dynamite.allow_remote_dynamite", false, false, com.google.android.gms.measurement.internal.zzde.zza);
        zzbk = zza("measurement.sdk.collection.validate_param_names_alphabetical", false, false, com.google.android.gms.measurement.internal.zzdd.zza);
        zzbl = zza("measurement.collection.event_safelist", true, true, com.google.android.gms.measurement.internal.zzdf.zza);
        zzbm = zza("measurement.service.audience.scoped_filters_v27", true, true, com.google.android.gms.measurement.internal.zzdi.zza);
        zzbn = zza("measurement.service.audience.session_scoped_event_aggregates", true, true, com.google.android.gms.measurement.internal.zzdh.zza);
        zzbo = zza("measurement.service.audience.session_scoped_user_engagement", true, true, com.google.android.gms.measurement.internal.zzdk.zza);
        zzbp = zza("measurement.service.audience.scoped_engagement_removal_when_session_expired", true, true, com.google.android.gms.measurement.internal.zzdj.zza);
        zzbq = zza("measurement.client.audience.scoped_engagement_removal_when_session_expired", true, true, com.google.android.gms.measurement.internal.zzdm.zza);
        zzbr = zza("measurement.service.audience.remove_disabled_session_scoped_user_engagement", false, false, com.google.android.gms.measurement.internal.zzdl.zza);
        zzbs = zza("measurement.service.audience.use_bundle_timestamp_for_property_filters", true, true, com.google.android.gms.measurement.internal.zzdo.zza);
        zzbt = zza("measurement.service.audience.fix_prepending_previous_sequence_timestamp", true, true, com.google.android.gms.measurement.internal.zzdn.zza);
        zzdj = zza("measurement.service.audience.invalidate_config_cache_after_app_unisntall", true, true, com.google.android.gms.measurement.internal.zzdq.zza);
        zzbu = zza("measurement.service.audience.fix_skip_audience_with_failed_filters", true, true, com.google.android.gms.measurement.internal.zzds.zza);
        zzbv = zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", false, false, com.google.android.gms.measurement.internal.zzdr.zza);
        zzbw = zza("measurement.audience.refresh_event_count_filters_timestamp", false, false, com.google.android.gms.measurement.internal.zzdu.zza);
        zzbx = zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", false, false, com.google.android.gms.measurement.internal.zzdt.zza);
        zzby = zza("measurement.sdk.collection.retrieve_deeplink_from_bow_2", true, true, com.google.android.gms.measurement.internal.zzdw.zza);
        zzbz = zza("measurement.app_launch.event_ordering_fix", false, false, com.google.android.gms.measurement.internal.zzdv.zza);
        zzca = zza("measurement.sdk.collection.last_deep_link_referrer2", true, true, com.google.android.gms.measurement.internal.zzdy.zza);
        zzcb = zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", false, false, com.google.android.gms.measurement.internal.zzdx.zza);
        zzcc = zza("measurement.sdk.collection.last_gclid_from_referrer2", false, false, com.google.android.gms.measurement.internal.zzea.zza);
        zzcd = zza("measurement.sdk.collection.worker_thread_referrer", true, true, com.google.android.gms.measurement.internal.zzdz.zza);
        zzce = zza("measurement.sdk.collection.enable_extend_user_property_size", true, true, com.google.android.gms.measurement.internal.zzeb.zza);
        zzcf = zza("measurement.upload.file_lock_state_check", false, false, com.google.android.gms.measurement.internal.zzee.zza);
        zzcg = zza("measurement.sampling.calculate_bundle_timestamp_before_sampling", true, true, com.google.android.gms.measurement.internal.zzed.zza);
        zzch = zza("measurement.ga.ga_app_id", false, false, com.google.android.gms.measurement.internal.zzeg.zza);
        zzci = zza("measurement.lifecycle.app_backgrounded_tracking", true, true, com.google.android.gms.measurement.internal.zzef.zza);
        zzcj = zza("measurement.lifecycle.app_in_background_parameter", false, false, com.google.android.gms.measurement.internal.zzei.zza);
        zzck = zza("measurement.integration.disable_firebase_instance_id", false, false, com.google.android.gms.measurement.internal.zzeh.zza);
        zzcl = zza("measurement.lifecycle.app_backgrounded_engagement", false, false, com.google.android.gms.measurement.internal.zzek.zza);
        zzcm = zza("measurement.service.fix_gmp_version", false, false, com.google.android.gms.measurement.internal.zzej.zza);
        zzcn = zza("measurement.collection.service.update_with_analytics_fix", false, false, com.google.android.gms.measurement.internal.zzem.zza);
        zzco = zza("measurement.service.disable_install_state_reporting", true, true, com.google.android.gms.measurement.internal.zzeo.zza);
        zzcp = zza("measurement.service.use_appinfo_modified", false, false, com.google.android.gms.measurement.internal.zzen.zza);
        zzcq = zza("measurement.client.firebase_feature_rollout.v1.enable", true, true, com.google.android.gms.measurement.internal.zzeq.zza);
        zzcr = zza("measurement.client.sessions.check_on_reset_and_enable", false, false, com.google.android.gms.measurement.internal.zzep.zza);
        zzcs = zza("measurement.config.string.always_update_disk_on_set", false, false, com.google.android.gms.measurement.internal.zzes.zza);
        zzct = zza("measurement.scheduler.task_thread.cleanup_on_exit", false, false, com.google.android.gms.measurement.internal.zzer.zza);
        zzcu = zza("measurement.upload.file_truncate_fix", false, false, com.google.android.gms.measurement.internal.zzeu.zza);
        zzcv = zza("measurement.lifecycle.app_background_timestamp_when_backgrounded", true, true, com.google.android.gms.measurement.internal.zzet.zza);
        zzcw = zza("measurement.engagement_time_main_thread", true, true, com.google.android.gms.measurement.internal.zzew.zza);
        zzcx = zza("measurement.sdk.referrer.delayed_install_referrer_api", false, false, com.google.android.gms.measurement.internal.zzev.zza);
        zzcy = zza("measurement.logging.improved_messaging_q4_2019_client", true, true, com.google.android.gms.measurement.internal.zzat.zza);
        zzcz = zza("measurement.logging.improved_messaging_q4_2019_service", true, true, com.google.android.gms.measurement.internal.zzaw.zza);
        zzda = zza("measurement.gold.enhanced_ecommerce.format_logs", false, false, com.google.android.gms.measurement.internal.zzav.zza);
        zzdb = zza("measurement.gold.enhanced_ecommerce.nested_param_daily_event_count", false, false, com.google.android.gms.measurement.internal.zzay.zza);
        zzdc = zza("measurement.gold.enhanced_ecommerce.upload_nested_complex_events", false, false, com.google.android.gms.measurement.internal.zzax.zza);
        zzdd = zza("measurement.gold.enhanced_ecommerce.log_nested_complex_events.dev", false, false, com.google.android.gms.measurement.internal.zzba.zza);
        zzde = zza("measurement.gold.enhanced_ecommerce.updated_schema.client.dev", false, false, com.google.android.gms.measurement.internal.zzaz.zza);
        zzdf = zza("measurement.gold.enhanced_ecommerce.updated_schema.service", false, false, com.google.android.gms.measurement.internal.zzbc.zza);
        zzdk = zza("measurement.collection.synthetic_data_mitigation", false, false, com.google.android.gms.measurement.internal.zzbb.zza);
        zzdg = zza("measurement.collection.configurable_service_limits.dev", false, false, com.google.android.gms.measurement.internal.zzbe.zza);
    }
}
